INSERT INTO article(title, content) VALUES('1', '123');
INSERT INTO article(title, content) VALUES('2', '456');
INSERT INTO article(title, content) VALUES('3', '789');
INSERT INTO member(id, email, password) VALUES(1, 'email@email.com', 'password123');
INSERT INTO member(id, email, password) VALUES(2, 'email2@gmail.com', 'password23');
INSERT INTO member(id, email, password) VALUES(3, 'emmail3@nate.com', 'password3');
INSERT INTO coffee(name, price) VALUES('아메리카노', '4500');
INSERT INTO coffee(name, price) VALUES('카페라떼', '5000');
INSERT INTO coffee(name, price) VALUES('카페모카', '5500');
INSERT INTO article(title, content) VALUES('당신의 인생 영화는?', '댓글 고');
INSERT INTO article(title, content) VALUES('당신의 소울 푸드는?', '댓글 고고');
INSERT INTO article(title, content) VALUES('당신의 취미는?', '댓글 고고고');
INSERT INTO comment(article_id, nickname, body) VALUES(4, 'Park', '굿 윌 헌팅');
INSERT INTO comment(article_id, nickname, body) VALUES(4, 'Kim', '아메리칸 셰프');
INSERT INTO comment(article_id, nickname, body) VALUES(4, 'Choi', '쇼생크 탈출');
INSERT INTO comment(article_id, nickname, body) VALUES(5, 'Park', '치킨');
INSERT INTO comment(article_id, nickname, body) VALUES(5, 'Kim', '피자');
INSERT INTO comment(article_id, nickname, body) VALUES(5, 'Choi', '떡볶이');
INSERT INTO comment(article_id, nickname, body) VALUES(6, 'Park', '조깅');
INSERT INTO comment(article_id, nickname, body) VALUES(6, 'Kim', '유튜브 시청');
INSERT INTO comment(article_id, nickname, body) VALUES(6, 'Choi', '독서');